// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonEvents: typeof import('~icons/carbon/events')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonShoppingCart: typeof import('~icons/carbon/shopping-cart')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
  }
}

export { }
