// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAccounting: typeof import('~icons/carbon/accounting')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPerson: typeof import('~icons/carbon/person')['default']
    CarbonShirt: typeof import('~icons/carbon/shirt')['default']
    CarbonShoppingCart: typeof import('~icons/carbon/shopping-cart')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
  }
}

export { }
